services:
  newsai:
    image: ghcr.io/shahzod1602/test:latest
    build: .
    container_name: newsai
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  newsai-football:
    image: ghcr.io/shahzod1602/test:latest
    container_name: newsai-football
    restart: unless-stopped
    env_file: .env.football
    volumes:
      - ./data-football:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
